# hydra/sweeper/optuna.yaml
# Base Optuna sweeper wiring; values are overridden by hpo configs.

defaults:
  - _self_

_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
study_name: null
storage: null
direction: maximize
n_trials: 1
timeout: null
n_jobs: ${env:OPTUNA_N_JOBS,1}
sampler:
  _target_: optuna.samplers.TPESampler
  seed: null
pruner:
  _target_: optuna.pruners.MedianPruner
  n_startup_trials: 5
params: {}
