# configs/system/hpc_supercloud.yaml
# MIT SuperCloud-friendly runtime defaults.

seed: 42
cudnn_deterministic: true
cudnn_benchmark: false

paths:
  cache_dir: /state/partition1/user/lerchen/cache
  data_root: /orcd/home/002/lerchen/code/cafa6
  results_root: /orcd/home/002/lerchen/code/results

mlflow:
  tracking_uri: file:/orcd/home/002/lerchen/code/mlruns
  artifact_root: file:/orcd/home/002/lerchen/code/mlruns
  experiment_name: pfagcn_supercloud
  run_name: pf-agcn-hpc

env:
  OMP_NUM_THREADS: 20
  MKL_NUM_THREADS: 20
  NUMEXPR_NUM_THREADS: 20
  TORCH_NUM_THREADS: 20
  HYDRA_FULL_ERROR: 1


slurm:
  job_name: pfagcn
  partition: xeon-g6-volta
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 20
  gpus_per_task: 1
  gres: gpu:volta:1
  time: "24:00:00"
  output_dir: logs/hpc