# configs/system/hpc_supercloud.yaml
# MIT SuperCloud-friendly runtime defaults.

seed: 42
cudnn_deterministic: true
cudnn_benchmark: false

paths:
  cache_dir: /state/partition1/user/lerchen/cache # currently useless;
  data_root: /orcd/home/002/lerchen/code/cafa6
  results_root: /orcd/home/002/lerchen/code/results

mlflow:
  tracking_uri: file:/orcd/home/002/lerchen/code/mlruns
  artifact_root: file:/orcd/home/002/lerchen/code/mlruns
  experiment_name: pfagcn_supercloud
  run_name: pf-agcn-hpc

env:
  OMP_NUM_THREADS: 20
  MKL_NUM_THREADS: 20
  NUMEXPR_NUM_THREADS: 20
  TORCH_NUM_THREADS: 20
  HYDRA_FULL_ERROR: 1