# paths and parameters for cafa data
sources:
  seqs_path: C:\Users\yoche\OneDrive - The University of Texas at Austin\Documents\pf_agcn\data\raw\toy_train.fasta
  terms_path: C:\Users\yoche\OneDrive - The University of Texas at Austin\Documents\pf_agcn\data\raw\terms_train_toy.tsv
  ia_path: C:\Users\yoche\OneDrive - The University of Texas at Austin\Documents\pf_agcn\data\raw\ia.txt  # optional override
  go_path: C:\Users\yoche\OneDrive - The University of Texas at Austin\Documents\pf_agcn\data\raw\go-basic.obo  # optional override

split:
  seed: 1337
  ratios:
    train: 0.8
    val: 0.1
    test: 0.1

train_csv: data/splits/train.csv
val_csv:   data/splits/val.csv
test_csv:  data/splits/test.csv
embeddings_npz: ${system.cache_dir}/esm1b_cafa.npz
go_prior_npz:   ${system.cache_dir}/go_prior_cafa.npz

go_prior:
  obo_path: ${hydra:runtime.cwd}/data/ontology/go-basic.obo
  train_split_csv: ${..train_csv}
  top_k:
    MF: 100
    BP: 100
    CC: 100

batch_size: 64
train_manifest: null
val_manifest: null
test_manifest: null
